### PR TITLE
New Assignments and Database

### PR DESCRIPTION
**Pull request by rsampdev**
1) Added end-to-end functionality for creating new assignments

2) Consolidates all database and user service functionality together

### CODE REVIEW

**Comment by jonathanjlin** [comment]
Ben and Mahima should leave a more detailed review first, but this is too large to be a single PR. Auto-generated files (.class files, anythign in target/*) should not be committed (a review of earlier commits/PRs would have caught that), and deleting those should be in a separate PR from all the code additions. .gitignore changes can also be in their own PR

**Comment by rsampdev** [comment]
> Ben and Mahima should leave a more detailed review first, but this is too large to be a single PR. Auto-generated files (.class files, anythign in target/*) should not be committed (a review of earlier commits/PRs would have caught that), and deleting those should be in a separate PR from all the code additions. .gitignore changes can also be in their own PR

Okay no problem, I'll make another local branch and rewind some of my commits and try to trim this down into some smaller PRs so it can be reviewed easier. I'll leave this PR up for now but if you think it's best I can close this one.

I reviewed the latest PRs earlier, the main branch didn't have a .gitignore to copy down so I added one to avoid the same issues with the /target folder files. I'll put up the gitignore PR first, so that the other ones after that won't have any issues.

**Review by BenLin00 — APPROVED** [review]
LGTM

**Review by mahimashanware — APPROVED** [review]
looks good and very organized!

**Pull request closed without merging**
